import {RideRepositoryDatabase} from "./RideRepository";
import Signup from "./Signup";
import GetAccount from "./GetAccount";
import GetRide from "./GetRide";
import RequestRide from "./RequestRide";
import Registry from "./Registry";
import {AccountRepositoryDatabase} from "./AccountRepository";
import {PgPromiseAdapter} from "./DatabaseConnection";
import {ExpressAdapter} from "./HttpServer";
import AccountController from "./AccountController";
import RideController from "./RideController";

const databaseConnection = new PgPromiseAdapter();
Registry.getInstance().provide("databaseConnection", databaseConnection);
const accountRepository = new AccountRepositoryDatabase();
Registry.getInstance().provide("accountRepository", accountRepository);
const rideRepository = new RideRepositoryDatabase();
Registry.getInstance().provide("rideRepository", rideRepository);
const signup = new Signup();
Registry.getInstance().provide("signup", signup);
const getAccount = new GetAccount();
Registry.getInstance().provide("getAccount", getAccount);
const requestRide = new RequestRide();
Registry.getInstance().provide("requestRide", requestRide);
const getRide = new GetRide();
Registry.getInstance().provide("getRide", getRide);
const httpServer = new ExpressAdapter();
Registry.getInstance().provide("httpServer", httpServer);
new AccountController();
new RideController();
httpServer.listen(3000);
