import {RideRepositoryDatabase} from "./infra/repository/RideRepository";
import Signup from "./application/usecase/Signup";
import GetAccount from "./application/usecase/GetAccount";
import GetRide from "./application/usecase/GetRide";
import RequestRide from "./application/usecase/RequestRide";
import Registry from "./infra/di/Registry";
import {AccountRepositoryDatabase} from "./infra/repository/AccountRepository";
import {PgPromiseAdapter} from "./infra/database/DatabaseConnection";
import {ExpressAdapter} from "./infra/http/HttpServer";
import AccountController from "./infra/controller/AccountController";
import RideController from "./infra/controller/RideController";

const databaseConnection = new PgPromiseAdapter();
Registry.getInstance().provide("databaseConnection", databaseConnection);
const accountRepository = new AccountRepositoryDatabase();
Registry.getInstance().provide("accountRepository", accountRepository);
const rideRepository = new RideRepositoryDatabase();
Registry.getInstance().provide("rideRepository", rideRepository);
const signup = new Signup();
Registry.getInstance().provide("signup", signup);
const getAccount = new GetAccount();
Registry.getInstance().provide("getAccount", getAccount);
const requestRide = new RequestRide();
Registry.getInstance().provide("requestRide", requestRide);
const getRide = new GetRide();
Registry.getInstance().provide("getRide", getRide);
const httpServer = new ExpressAdapter();
Registry.getInstance().provide("httpServer", httpServer);
new AccountController();
new RideController();
httpServer.listen(3000);
